In [43]:
import pandas as pd
import os

In [44]:
pwd

'C:\\Users\\User'

In [45]:
df = pd.read_csv('C:/Users/User/Music/paris_olympics_results.csv', encoding='ISO-8859-1')
df.head()

,Country,Medal,Name,Sport,Event,Date
0,Albania,Bronze,Chermen Valiev,Wrestling,Men's freestyle 74 kg,8/10/2024
1,Albania,Bronze,Islam Dudaev,Wrestling,Men's freestyle 65 kg,8/11/2024
2,Algeria,Gold,Kaylia Nemour,Gymnastics,Women's uneven bars,8/4/2024
3,Algeria,Gold,Imane Khelif,Boxing,Women's 66 kg,8/9/2024
4,Algeria,Bronze,Djamel Sedjati,Athletics,Men's 800 m,8/10/2024

In [46]:
df.tail()

,Country,Medal,Name,Sport,Event,Date
1034,Uzbekistan,Gold,Razambek Zhamalov,Wrestling,Men's freestyle 74 kg,8/10/2024
1035,Uzbekistan,Silver,Svetlana Osipova,Taekwondo,Women's +67 kg,8/10/2024
1036,Uzbekistan,Gold,Ulugbek Rashitov,Taekwondo,Men's 68 kg,8/8/2024
1037,Zambia,Bronze,Muzala Samukonga,Athletics,Men's 400 m,8/7/2024
1038,Zambia,Bronze,Muzala Samukonga,Athletics,Men's 400 m,8/7/2024

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  1039 non-null   object
 1   Medal    903 non-null    object
 2   Name     1039 non-null   object
 3   Sport    1037 non-null   object
 4   Event    1039 non-null   object
 5   Date     1039 non-null   object
dtypes: object(6)
memory usage: 48.8+ KB

In [48]:
df.shape

(1039, 6)

In [49]:
df.describe()

,Country,Medal,Name,Sport,Event,Date
count,1039,903,1039,1037,1039,1039
unique,92,5,799,38,399,17
top,USA,Bronze,Lennart van Lierop\nFinn Florijn\nTone Wieten\...,Athletics,Women's tournament,8/10/2024
freq,126,345,81,145,22,110

In [50]:
df.values

array([['Albania', 'Bronze', 'Chermen Valiev', 'Wrestling',
        "Men's freestyle 74 kg", '8/10/2024'],
       ['Albania', 'Bronze', 'Islam Dudaev', 'Wrestling',
        "Men's freestyle 65 kg", '8/11/2024'],
       ['Algeria', 'Gold', 'Kaylia Nemour', 'Gymnastics',
        "Women's uneven bars", '8/4/2024'],
       ...,
       ['Uzbekistan', 'Gold', 'Ulugbek Rashitov', 'Taekwondo',
        "Men's 68 kg", '8/8/2024'],
       ['Zambia', 'Bronze', 'Muzala Samukonga', 'Athletics',
        "Men's 400 m", '8/7/2024'],
       ['Zambia', 'Bronze', 'Muzala Samukonga', 'Athletics',
        "Men's 400 m", '8/7/2024']], dtype=object)

In [51]:
df.columns

Index(['Country', 'Medal', 'Name', 'Sport', 'Event', 'Date'], dtype='object')

In [52]:
df.index

RangeIndex(start=0, stop=1039, step=1)

In [53]:
df.sort_values(["Name", "Event", "Date"], ascending = [True, False, True])

,Country,Medal,Name,Sport,Event,Date
898,USA,Bronze,Aaron Brooks,Wrestling,Men's freestyle 86 kg,8/9/2024
678,Malaysia,Bronze,Aaron ChiaSoh Wooi Yik,Badminton,Men's doubles,8/4/2024
1024,Uzbekistan,Gold,Abdumalik Khalokov,Boxing,Men's featherweight,8/10/2024
131,Canada,Silver,Abigail DentCaileigh FilmerKasia Gruchalla-Wes...,Rowing,Women's eight,8/3/2024
651,Kenya,Bronze,Abraham Kibiwot,Athletics,Men's 3000 m steeplechase,8/7/2024
...,...,...,...,...,...,...
837,Spain,Bronze,Álvaro Martín,Athletics,Men's 20 km walk,8/1/2024
828,Spain,Gold,Álvaro Martín\nMaría Pérez,Athletics,Mixed marathon walk relay,8/7/2024
248,Columbia,Silver,Ángel Barajas,Gymnastics,Men's horizontal bar,8/5/2024
683,Mexico,Bronze,Ángela RuizAlejandra ValenciaAna Paula Vázquez,Archery,Women's team,7/28/2024
323,France,Silver,Élodie Clouvel,Modern pentathlon,Women's individual,8/11/2024

In [54]:
is_gymnastics = df["Sport"] == "Skateboarding"
is_gold = df["Medal"] == "Gold"

df[is_gymnastics & is_gold]

      Country Medal           Name          Sport         Event      Date
15  Australia  Gold     Arisa Trew  Skateboarding  Women's park  8/6/2024
47  Australia  Gold  Keegan Palmer  Skateboarding    Men's park  8/7/2024

In [55]:
# Rename "Country" column to "NOC"
df.rename(columns = {"Country": "NOC"}, inplace = True)
print(df)

             NOC   Medal               Name       Sport  \
0        Albania  Bronze     Chermen Valiev   Wrestling
1        Albania  Bronze       Islam Dudaev   Wrestling
2        Algeria    Gold      Kaylia Nemour  Gymnastics
3        Algeria    Gold       Imane Khelif      Boxing
4        Algeria  Bronze     Djamel Sedjati   Athletics
...          ...     ...                ...         ...
1034  Uzbekistan    Gold  Razambek Zhamalov   Wrestling
1035  Uzbekistan  Silver   Svetlana Osipova   Taekwondo
1036  Uzbekistan    Gold   Ulugbek Rashitov   Taekwondo
1037      Zambia  Bronze   Muzala Samukonga   Athletics
1038      Zambia  Bronze   Muzala Samukonga   Athletics

                      Event       Date
0     Men's freestyle 74 kg  8/10/2024
1     Men's freestyle 65 kg  8/11/2024
2       Women's uneven bars   8/4/2024
3             Women's 66 kg   8/9/2024
4               Men's 800 m  8/10/2024
...                     ...        ...
1034  Men's freestyle 74 kg  8/10/2024
1035         Women's +67 kg  8/10/2024
1036            Men's 68 kg   8/8/2024
1037            Men's 400 m   8/7/2024
1038            Men's 400 m   8/7/2024

[1039 rows x 6 columns]

In [56]:
japan_medal_mapping = {
    'Akari Fujinami': 'Gold',
    'Ami Yuasa': 'Gold',
    'Coco Yoshizawa': 'Gold',
    'Daichi Takatani': 'Silver',
    'Haruka Funakubo': 'Bronze',
    'Haruka Kitaguchi': 'Gold',
    'Hideki Matsuyama': 'Bronze',
    'Hifumi Abe': 'Gold',
    'Hina Hayata': 'Bronze',
    'Kenichiro Fumita': 'Gold',
    'Koki Kano': 'Gold',
    'Kokona Hiraki': 'Silver',
    'Kotaro Kiyooka': 'Gold',
    'Liz Akama': 'Silver',
    'Nao Kusaka': 'Gold',
    'Natsumi Tsunoda': 'Gold',
    'Nonoka Ozaki': 'Bronze',
    'Rei Higuchi': 'Gold',
    'Rikuto Tamai': 'Silver',
    'Ryuju Nagayama': 'Bronze',
    'Sakura Motoki': 'Gold',
    'Sanshiro Murao': 'Silver',
    'Shinnosuke Oka': 'Gold',
    'Shinnosuke Oka': 'Gold',
    'Shinnosuke Oka': 'Bronze',
    'Soichi Hashimoto': 'Bronze',
    'Sorato Anraku': 'Silver',
    'Taishu Sato': 'Silver',
    'Takaaki Sugino\nShinnosuke Oka\nDaiki Hashimoto\nKazuma Kaya\nWataru Tanigawa': 'Gold',
    'Kazuki limura\nKyosuke Matsuyama\nTakahiro Shikine\nYudai Nagano': 'Gold',
    'Akira Komata\nKoki Kano\nMasaru Yamada\nKazuyasu Minobe': 'Silver',
    'Uta Abe\nSoichi Hashimoto\nMiku Tashiro\nSanshiro Murao\nRika Takayama\nTatsuru Saito\nTakanori Nagase\nAaron Wold\nHaruka Funakubo\nAkira Sone\nRyuju Nagayama\nNatsumi Tsunoda\nHifumi Abe': 'Gold',
    'Keiju Okada\nMiho Yoshioka': 'Silver',
    'Hina Hayata\nMiwa Harimoto\nMiu Hirano': 'Silver',
    'Yoshiaki Oiwa\nKazuma Tomoto\nToshiyuki Tanaka\nRyuzo Kitajima': 'Bronze',
    'Sera Azuma\nYuka Ueno\nKarin Miyawaki\nKomaki Kikuchi': 'Bronze',
    'Yuta Watanabe\nArisa Higashino': 'Bronze',
    'Nami Matsuyama\nChiharu Shida': 'Bronze',
    'Risa Takashima\nSeri Ozaki\nMisaki Emura\nShihomi Fukushima': 'Bronze',
    'Takanori Nagase': 'Gold',
    'Tomoyuki Matsushita': 'Silver',
    'Tsugumi Sakurai': 'Gold',
    'Yui Susaki': 'Bronze',
    'Yuka Kagami': 'Gold',
    'Yuto Horigome': 'Gold'
}

In [57]:
df["Medal"] = df["Medal"].fillna(df["Name"].map(japan_medal_mapping))

In [67]:
china_medal_mapping = { 
    'Cao Liguo': 'Silver',
    'Cao Yuan': 'Gold',
    'Chang Yani': 'Bronze',
    'Chang Yuan': 'Gold',
    'Chen Meng': 'Gold',
    'Chen Yiwen': 'Gold',
    'Chen Yuxi': 'Silver',
    'Deng Lijuan': 'Silver',  
    'Deng Yawen': 'Gold',
    'Fan Zhendong': 'Gold',
    'Feng Bin': 'Silver',
    'Feng Ziqi': 'Bronze',
    'Guo Qing': 'Silver',
    'He Bingjiao': 'Silver',
    'Hong Kexin': 'Bronze',
    'Hou Zhihui': 'Gold',
    'Huang Yuting': 'Silver',
    'Huang Yuting\nSheng Lihao': 'Gold',
    'Chang Yani\nChen Yiwen': 'Gold',
    'Lian Junjie\nYang Hao': 'Gold',
    'Wang Chuqin\nSun Yingsha': 'Gold',
    'Chen Yuxi\nQuan Hongchan': 'Gold',
    'Long Daoyi\nWang Zongyuan': 'Gold',
    'Zhng Siwei\nHuang Yaqiong': 'Gold',
    'Chen Qingchen\nJia Yifan': 'Gold',
    'Xu Jiayu\nQin Haiyang\nSun Jiajun\nPan Zhanle\nWang Changhao': 'Gold',
    'Chang Hao\nFeng Yu\nWang Ciyue\nWang Liuyi\nWang Qianyi\nXiang Binxuan\nXiao Yanning\nZhang Yayi': 'Gold',
    'Xu Shixiao\nSun Mengya': 'Gold',
    'Fan Zhendong\nMa Long\nWang Chuqin': 'Gold',
    'Ding Xinyi\nGuo Qiqi\nHao Ting\nHuang Zhangjiayang\nPu Yanzhu\nWang Lanjing': 'Gold',
    'Chen Meng\nSun Yingsha\nWang Manyu': 'Gold',
    'Wang Liuyi\nWang Qianyi': 'Gold',
    'An Qixuan\nLi Jiaman\nYang Xiaolei': 'Silver',
    'Liu Yang\nSu Weide\nXiao Ruoteng\nZhang Boheng\nZou Jingyuan': 'Silver',
    'Wang Xinyu\nZhang Zhizhen': 'Silver',
    'Liu Shengshu\nTan Ning': 'Silver',
    'Qin Haiyang\nYang Junxuan\nXu Jiayu\nPan Zhanle\nTang Qianting\nZhang Yufei': 'Silver',
    'Liang Weikeng\nWang Chang': 'Silver',
    'China womens national field hockey team\nYe Jiao\nGu Bingfeng\nYang Liu\nZhang Ying\nChen Yi\nMa Ning\nLi Hong\nOu Zixia\nDan Wen\nZou Meirong\nHe Jiangxin\nFan Yunxia\nChen Yang\nXu Wenyu\nZhong Jiaqi\nTan Jinzhuang\nYu Anhui': 'Silver',
    'Cheng Yuije\nWu Qingfeng\nYang Junxuan\nYu Yiting\nZhang Yufei': 'Bronze',
    'Ge Chutong\nKong Yaqi\nLi Bingjie\nLiu Yaxin\nTang Muhan\nYang Junxuan': 'Bronze',
    'Wan Letian\nTang Qianting\nZhang Yufei\nYang Junxuan\nWang Xue`er\nYu Yiting\nWu Qingfeng': 'Bronze',
    'Jiang Yiting\nLyu Jianlin': 'Bronze',
    'Li Fabin': 'Gold',
    'Li Qian': 'Gold',
    'Li Wenwen': 'Gold',
    'Li Yuehong': 'Gold',
    'Liang Yushuai': 'Bronze',
    'Lin Xiyu': 'Bronze',
    'Liu Hao\nJi Bowen': 'Gold',
    'Liu Huanhua': 'Gold',
    'Liu Qingyi': 'Bronze',
    'Liu Yang': 'Gold',
    'Liu Yukun': 'Gold',
    'Luo Shifang': 'Gold',  
    'Ma Zhenzhao': 'Bronze',
    'Meng Lingzhe': 'Bronze',
    'Pan Zhanle': 'Gold',
    'Pang Qianyu': 'Bronze',
    'Qi Ying': 'Silver',
    'Qiu Qiyuan': 'Silver',
    'Quan Hongchan': 'Gold',
    'Sheng Lihao': 'Gold',
    'Song Jiayuan': 'Bronze',
    'Sun Yingsha': 'Silver',
    'Tang Qianting': 'Silver',
    'Wang Shun': 'Bronze',
    'Wang Xinjie': 'Bronze',
    'Wang Zisai': 'Silver',
    'Wang Zongyuan': 'Silver',
    'Wu Peng': 'Silver',
    'Wu Yu': 'Gold',
    'Xiao Ruoteng': 'Bronze',
    'Xie Siyi': 'Gold',
    'Xie Yu': 'Gold',
    'Xu Jiayu': 'Silver',
    'Yan Langyu': 'Bronze',
    'Yang Jiayu': 'Gold',
    'Yang Liu': 'Silver',  
    'Yang Wenlu': 'Silver',
    'Zhang Boheng': 'Silver',
    'Zhang Boheng': 'Bronze',
    'Zhang Qiongyue': 'Bronze',
    'Zhang Yufei': 'Bronze',
    'Zhang Yufei': 'Bronze',
    'Zhang Yufei': 'Bronze',
    'Zhao Jie': 'Bronze',
    'Zheng Qinwen': 'Gold',
    'Zhou Yaqin': 'Silver',
    'Zou Jingyuan': 'Gold',
    'Zou Jingyuan': 'Silver'
}

In [68]:
df["Medal"] = df["Medal"].fillna(df["Name"].map(china_medal_mapping))

In [69]:
df

,NOC,Medal,Name,Sport,Event,Date
0,Albania,Bronze,Chermen Valiev,Wrestling,Men's freestyle 74 kg,8/10/2024
1,Albania,Bronze,Islam Dudaev,Wrestling,Men's freestyle 65 kg,8/11/2024
2,Algeria,Gold,Kaylia Nemour,Gymnastics,Women's uneven bars,8/4/2024
3,Algeria,Gold,Imane Khelif,Boxing,Women's 66 kg,8/9/2024
4,Algeria,Bronze,Djamel Sedjati,Athletics,Men's 800 m,8/10/2024
...,...,...,...,...,...,...
1034,Uzbekistan,Gold,Razambek Zhamalov,Wrestling,Men's freestyle 74 kg,8/10/2024
1035,Uzbekistan,Silver,Svetlana Osipova,Taekwondo,Women's +67 kg,8/10/2024
1036,Uzbekistan,Gold,Ulugbek Rashitov,Taekwondo,Men's 68 kg,8/8/2024
1037,Zambia,Bronze,Muzala Samukonga,Athletics,Men's 400 m,8/7/2024
1038,Zambia,Bronze,Muzala Samukonga,Athletics,Men's 400 m,8/7/2024

In [70]:
df.to_csv('C:/Users/User/Music/paris_olympics_results.csv', index=False, encoding='ISO-8859-1')